<?php

/*
 * REPLACE THE VALUES BELOW WITH YOUR EdFi CREDENTIALS
 * AND RENAME THIS FILE TO "config.php"
 */

define("CLIENT_ID", "YOURCLIENTIDGOESHERE");
define("CLIENT_SECRET" , "YOURCLIENTSECRETGOESHERE"); 

?>